### PR TITLE
[gsoc2020] Remove django-netjsonconfig #184

### LINKED ISSUE #184: [gsoc2020] Merged Modules remove django-netjsonconfig
After https://github.com/openwisp/openwisp-controller/pull/190 is merged, remove django-netjsonconfig from ansible-openwisp2.

### PR DESCRIPTION
**Pull request by atb00ker**
Manually tested by creating a device! :smile:

Closes #184

### CODE REVIEW

**Comment by atb00ker** [comment]
travis failing because new version of controller is not yet release! :smile:

**Comment by nemesisdesign** [comment]
Update regarding:
 
> ```python
> DJANGO_X509_CA_MODEL = 'pki.Ca'
> DJANGO_X509_CERT_MODEL = 'pki.Cert' 
> ```

This PR should make this not necessary: https://github.com/openwisp/openwisp-controller/pull/256.

**Comment by pandafy** [comment]
Since openwisp-controller 0.8.0 is release, I think we should progress with this PR.

**Review by nemesisdesign — APPROVED** [review]
Let's move on and break things.

**Pull request merged**
