### PR TITLE
[change] Use freeradius 3.2 on Ubuntu 22.04 #401

### LINKED ISSUE #401: [enhancement] Use FreeRADIUS 3.2 for installation
The role installs FreeRADIUS 3.0.x which fails on Ubuntu 22.04.1 because `libjson-c4` package is not available. 

Moreover, the [FreeRADIUS documentation](https://networkradius.com/packages/#fr30-ubuntu) does not mention support for Ubuntu 22.04 for FreeRADIUS 3.0. 

We should update the role to install FreeRADIUS 3.2

### PR DESCRIPTION
**Pull request by Aryamanz29**
Closes #401

### CODE REVIEW

**Review by pandafy — CHANGES_REQUESTED** [review]
@Aryamanz29 I have concerns on how these changes would affect an existing installation of FreeRADIUS on Ubuntu 22.04. I suspect that running these changes against an existing installation would result in installing FreeRADIUS 3.2 alongside FreeRADIUS 3.0. 

Also, changing `freeradius_dir` variable like this would be a breaking change to configuration of existing installations.

We have to be more careful with change. I have these suggestion for the flow

- If the OS is Ubuntu 22.04.1 (jammy), check if freeradius is already installed. We can check this with  `freeradius -v | sed -n 2p` which also gives us the version 
    - If the version of 3.0.x, do not change `freeradius_dir` variable, else update the variable to `/etc/freeradius` 
- If the OS is Ubuntu 22,04.1 (jammy) and FreeRADIUS is not installed (new installation), then update the `freeradius_dir` variable.

**Comment by pandafy** [comment]
Hi @Aryamanz29! I will be taking over this PR. Can you please push any changes you have locally?

**Comment by pandafy** [comment]
@nemesisdesign the builds are failing because `importlib-metadata` is incompatible with Python 3.7.  I have already pinned the version in [openwissp-utils](https://github.com/openwisp/openwisp-utils/blob/163b4d4aae3c1a0aa5b58bf612fe081dba812922/setup.py#L49-L51). Should I update the role to use the development version of openwisp-utils?

**Review by nemesisdesign — COMMENTED** [review]
> @nemesisdesign the builds are failing because `importlib-metadata` is incompatible with Python 3.7. I have already pinned the version in [openwissp-utils](https://github.com/openwisp/openwisp-utils/blob/163b4d4aae3c1a0aa5b58bf612fe081dba812922/setup.py#L49-L51). Should I update the role to use the development version of openwisp-utils?

Let's release a new bugfix version of openwisp-utils with that fix.

**Review by nemesisdesign — APPROVED** [review]

**Pull request merged**
