### PR TITLE
Run local testing with molecule

### LINKED ISSUE #208: [docs] Instructions on how to run tests outdated
It seems the instructions on how to run tests are outdated: https://github.com/openwisp/ansible-openwisp2#how-to-run-tests.

Ideally we should have a simpler section with less steps, I hope we can do that.

### PR DESCRIPTION
**Pull request by hispanico**
- Added molecule scenario for local test
- Updated local test documentation

Related to #208

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
Haven't checked this yet but will do asap. @atb00ker @PabloCastellano maybe you can give a look at this, especially the instruction to run tests.

**Review by nemesisdesign — COMMENTED** [review]
Thanks @hispanico, looks very good.

Trying to run the test command suggested in the README gave me this weird result:

```
TASK [Wait for instance(s) creation to complete] *******************************
    FAILED - RETRYING: Wait for instance(s) creation to complete (300 retries left).
    FAILED - RETRYING: Wait for instance(s) creation to complete (299 retries left).
    FAILED - RETRYING: Wait for instance(s) creation to complete (298 retries left).
    FAILED - RETRYING: Wait for instance(s) creation to complete (297 retries left).
    FAILED - RETRYING: Wait for instance(s) creation to complete (296 retries left).
    FAILED - RETRYING: Wait for instance(s) creation to complete (295 retries left).
    FAILED - RETRYING: Wait for instance(s) creation to complete (294 retries left).
```

I installed the pip dependencies and started the docker service before launching the test.

Any idea on why this is happening? Maybe some permissions are missing?
I tried to update the docker pip package as suggested in this issue: https://github.com/ansible-community/molecule/issues/1384 with no luck.

**Comment by atb00ker** [comment]
> I installed the pip dependencies and started the docker service before launching the test.

I was having the same problem, it was because of slow connection on my end, I downloaded the docker images beforehand:

```
    docker pull geerlingguy/docker-ubuntu2004-ansible:latest
    docker pull geerlingguy/docker-ubuntu1804-ansible:latest
    docker pull geerlingguy/docker-debian10-ansible:latest
```

**Comment by nemesisdesign** [comment]
> > I installed the pip dependencies and started the docker service before launching the test.
> 
> @nemesisdesign
> I was having the same problem, it was because of slow connection on my end, I downloaded the docker images beforehand:
> 
> ```
>     docker pull geerlingguy/docker-ubuntu2004-ansible:latest
>     docker pull geerlingguy/docker-ubuntu1804-ansible:latest
>     docker pull geerlingguy/docker-debian10-ansible:latest
> ```
> 
> Somehow, after that, `[Stouts.postfix : Install requirements (Debian)]` fails for me, but it didn't fail in the [travis test](https://travis-ci.org/github/openwisp/ansible-openwisp2/builds/732383925?utm_source=github_status&utm_medium=notification). So much for a docker environment.
> 
> Please let me know if I should add these changes: [2156907](https://github.com/openwisp/ansible-openwisp2/commit/2156907636acf2615510a077c75a3e517eaae97c)

Yes! Please proceed to push it to this branch :+1:

**Comment by atb00ker** [comment]
> Yes! Please proceed to push it to this branch :+1:

Done! :smile:

**Review by nemesisdesign — APPROVED** [review]
Thanks @hispanico @atb00ker :+1: :clap:

**Pull request merged**
